{{--
  Template Name: FAQ
--}}
@extends('layouts.app')

@php
$ctaHref = \App\cta_href(get_theme_mod('rv_cta_url', '/contact/'));

$faqPid = get_queried_object_id();

// The design process, as a guided flow graphic (editable in Page content).
$process = \App\field_rows('fproc_items', [
  ['title' => __('Discover', 'sage'), 'text' => __('A short, no-pressure call to learn your business, your customers, and what a win looks like.', 'sage')],
  ['title' => __('Plan', 'sage'), 'text' => __('I map your pages and the path from stranger to phone call — before any design begins.', 'sage')],
  ['title' => __('Design & write', 'sage'), 'text' => __('Visuals and copy that sound like you: warm, clear, local, and built to earn trust fast.', 'sage')],
  ['title' => __('Build', 'sage'), 'text' => __('Hand-coded, fast, mobile-first, and accessible from the very first line of markup.', 'sage')],
  ['title' => __('Launch', 'sage'), 'text' => __('Domain, speed, security, and local SEO — your site goes live clean and ready to be found.', 'sage')],
  ['title' => __('Support', 'sage'), 'text' => __('Training, a 30-day workmanship warranty, and a real person a phone call away.', 'sage')],
], $faqPid);

// FAQ rows (editable in Page content); grouped by their Category, order preserved.
$faqRows = \App\field_rows('faq_items', [
  ['cat' => __('Pricing & timeline', 'sage'), 'q' => __('How much does a website cost?', 'sage'), 'a' => __('Most local sites land between a few hundred and a few thousand dollars, depending on pages and features. Every package is fixed-price, so you know the number before we start — try the estimator on the Tools page for a ballpark.', 'sage')],
  ['cat' => __('Pricing & timeline', 'sage'), 'q' => __('How long does it take?', 'sage'), 'a' => __('A working first draft in about three business days, and most sites launch in 7–10 days. Speed comes from a disciplined process, not corner-cutting.', 'sage')],
  ['cat' => __('Pricing & timeline', 'sage'), 'q' => __('How does payment work?', 'sage'), 'a' => __('A fixed price agreed up front, a deposit to start, and the balance before launch. No hourly meter, no surprise invoices.', 'sage')],
  ['cat' => __('Working together', 'sage'), 'q' => __('Do I need to know anything technical?', 'sage'), 'a' => __('No. I handle the build, hosting setup, and launch. If you\'d like to make edits yourself, I\'ll show you the few simple things you\'ll actually use.', 'sage')],
  ['cat' => __('Working together', 'sage'), 'q' => __('What do you need from me to start?', 'sage'), 'a' => __('Not much: a bit about your business and customers, your logo and any photos you have, and your hours and services. I turn that into a first draft and chase down the rest as we go.', 'sage')],
  ['cat' => __('Working together', 'sage'), 'q' => __('How many rounds of changes do I get?', 'sage'), 'a' => __('One consolidated review round is built into every project — you see the real site early, gather your feedback, and I apply it in a single clean pass. A care plan covers changes after launch.', 'sage')],
  ['cat' => __('Working together', 'sage'), 'q' => __('Do you use AI to build my website?', 'sage'), 'a' => __('Your site is designed and built by me, by hand — not generated by a machine. I use AI the way I\'d use any modern tool: to speed up early drafts and research, so I can spend more time on the parts that matter. Every design choice, every word in your voice, and the final build get my judgment. You\'re hiring a person who\'s accountable for the result — the tools just help me get there faster and keep your price fair.', 'sage')],
  ['cat' => __('Getting found in Gettysburg', 'sage'), 'q' => __('Do you do local SEO?', 'sage'), 'a' => __('Yes — it\'s built into every site. Google Business Profile setup, on-page SEO, LocalBusiness structured data, and location pages so nearby customers across Gettysburg and Adams County find you first.', 'sage')],
  ['cat' => __('Getting found in Gettysburg', 'sage'), 'q' => __('Will my business show up on Google Maps?', 'sage'), 'a' => __('That\'s the goal. I set up and optimize your Google Business Profile and keep your name, address, and phone consistent everywhere, so you\'re a strong candidate for the local "map pack" — the top three results people tap first.', 'sage')],
  ['cat' => __('Getting found in Gettysburg', 'sage'), 'q' => __('Do you build pages for the towns I serve?', 'sage'), 'a' => __('When it helps, yes. If you serve more than one town — say Gettysburg, Biglerville, Littlestown, New Oxford, and Hanover — I can build clear, useful location pages so you can rank in each one, not just your home base.', 'sage')],
  ['cat' => __('Getting found in Gettysburg', 'sage'), 'q' => __('Can you set up my Google Business Profile?', 'sage'), 'a' => __('Absolutely. I\'ll claim or clean up your profile, choose the right categories, add hours, photos, and services, and point it at your new site — often the single biggest local-search win for a small business.', 'sage')],
  ['cat' => __('Your site, ownership & support', 'sage'), 'q' => __('Do I own my site?', 'sage'), 'a' => __('Always. You own the domain, the hosting account, and the site itself. No lock-in, and you can cancel a care plan anytime and keep everything.', 'sage')],
  ['cat' => __('Your site, ownership & support', 'sage'), 'q' => __('Do you handle hosting and domains?', 'sage'), 'a' => __('Yes — I set both up in your name and can manage them for you, or hand you the keys. Either way it\'s yours, and you\'re never locked in.', 'sage')],
  ['cat' => __('Your site, ownership & support', 'sage'), 'q' => __('What if I already have a website?', 'sage'), 'a' => __('Then Website Rescue may be all you need — I can repair, restyle, and speed up what you have instead of starting over.', 'sage')],
  ['cat' => __('Your site, ownership & support', 'sage'), 'q' => __('What happens after launch?', 'sage'), 'a' => __('You get a 30-day workmanship warranty, a training video, and the option of a Care & Grow plan for updates, backups, and edits. Or take the keys and run it yourself.', 'sage')],
  ['cat' => __('Your site, ownership & support', 'sage'), 'q' => __('Are the sites accessible?', 'sage'), 'a' => __('Accessibility-first is the standard here — I build to WCAG 2.2 AA and check every page before launch, so the site works for everyone (and tends to rank better, too).', 'sage')],
  ['cat' => __('Local & logistics', 'sage'), 'q' => __('Do you only work with Gettysburg businesses?', 'sage'), 'a' => __('Gettysburg and Adams County are home base, but I work with small businesses throughout South Central PA — York, Franklin, and neighboring counties included. Farther away is fine too; most of the work happens over a call and a shared screen.', 'sage')],
  ['cat' => __('Local & logistics', 'sage'), 'q' => __('Do we have to meet in person?', 'sage'), 'a' => __('Only if you want to. Being local means I can meet face-to-face around Gettysburg when it helps — but plenty of projects run entirely over calls, email, and a shared screen. Whatever\'s easiest for you.', 'sage')],
], $faqPid);

$faqGroups = [];
$faqs = [];
foreach ($faqRows as $r) {
    $cat = \App\strip_field_markers((string) ($r['cat'] ?? ''));
    $faqGroups[$cat][] = $r;
    $faqs[] = [\App\strip_field_markers((string) ($r['q'] ?? '')), \App\strip_field_markers((string) ($r['a'] ?? ''))];
}
@endphp

@section('content')
  <section class="rv-hero">
    <span class="rv-stripe" aria-hidden="true"></span>
    @include('partials.hero-bg', ['fallback' => \App\stock_image('process')])
    <div class="rv-shell rv-hero-inner">
      {!! \App\eyebrow(\App\field('hero_eyebrow', __('FAQ', 'sage'))) !!}
      <h1 class="rv-hero-title">{{ \App\field('hero_title', __('Questions,', 'sage')) }} <em class="rv-accent">{{ \App\field('hero_accent', __('answered.', 'sage')) }}</em></h1>
      <p class="rv-hero-sub">{{ \App\field('hero_lede', __('What local owners ask before we start. Don\'t see yours? Ask.', 'sage')) }}</p>
      <div class="rv-hero-actions">
        <a class="rv-btn {{ \App\hero_btn_class(\App\field('hero_btn1_style',''), 'rv-btn-primary') }}" href="{{ $ctaHref }}">{{ \App\field('hero_btn1', __('Ask your question', 'sage')) }}</a>
        <a class="rv-btn {{ \App\hero_btn_class(\App\field('hero_btn2_style',''), 'rv-btn-ghost') }}" href="#faqs">{{ \App\field('hero_btn2', __('Jump to the FAQs', 'sage')) }} &darr;</a>
      </div>
    </div>
  </section>

  {{-- DESIGN PROCESS — GUIDED GRAPHIC --}}
  <section class="rv-shell rv-band rv-faqproc">
    <div class="rv-headstack">
      {!! \App\eyebrow(\App\field('fproc_eyebrow', __('How it works', 'sage'))) !!}
      <h2 class="rv-section-title">{{ \App\field('fproc_title', __('Your project,', 'sage')) }} <em class="rv-accent">{{ \App\field('fproc_accent', __('step by step.', 'sage')) }}</em></h2>
      <p class="rv-page-intro">{{ \App\field('fproc_intro', __('No mystery, no months of silence. Here\'s the exact path every Ridges & Valleys project follows — from the first call in Gettysburg to a site that\'s live and getting found.', 'sage')) }}</p>
    </div>

    <ol class="rv-process" aria-label="{{ __('Design process, step by step', 'sage') }}">
      @foreach ($process as $i => $step)
        <li class="rv-process-step">
          <span class="rv-process-node" aria-hidden="true">{{ $i + 1 }}</span>
          <h3 class="rv-process-t">{{ $step['title'] ?? '' }}</h3>
          <p class="rv-process-d">{{ $step['text'] ?? '' }}</p>
        </li>
      @endforeach
    </ol>

    <p class="rv-process-note">{{ \App\field('fproc_note', __('Fixed price agreed up front · One clear round of changes · You own everything at the end.', 'sage')) }}</p>
  </section>

  {{-- FAQs — all open, grouped, with local content --}}
  <section class="rv-shell rv-band rv-band-alt rv-faqwrap" id="faqs">
    <div class="rv-headstack">
      {!! \App\eyebrow(\App\field('faqs_eyebrow', __('Straight answers', 'sage'))) !!}
      <h2 class="rv-section-title">{{ \App\field('faqs_title', __('Everything owners ask,', 'sage')) }} <em class="rv-accent">{{ \App\field('faqs_accent', __('answered in full.', 'sage')) }}</em></h2>
      <p class="rv-page-intro">{{ \App\field('faqs_intro', __('A local, independent web designer based in Gettysburg — here\'s the honest detail on cost, timing, local SEO, ownership, and how I work with businesses across Adams County and South Central PA.', 'sage')) }}</p>
    </div>

    @foreach ($faqGroups as $cat => $items)
      <div class="rv-faqcat">
        <h3 class="rv-faqcat-h">{{ $cat }}</h3>
        <div class="rv-faqgrid">
          @foreach ($items as $qa)
            <div class="rv-qa">
              <h4 class="rv-qa-q">{{ $qa['q'] ?? '' }}</h4>
              <p class="rv-qa-a">{{ $qa['a'] ?? '' }}</p>
            </div>
          @endforeach
        </div>
      </div>
    @endforeach
  </section>

  {!! \App\faq_schema($faqs) !!}

  <style>
    /* Guided process graphic */
    .rv-faqproc .rv-process{list-style:none;margin:clamp(2.5rem,5vw,3.5rem) 0 0;padding:0;display:grid;grid-template-columns:repeat(6,1fr);gap:1rem}
    .rv-process-step{position:relative;text-align:center}
    .rv-process-step:not(:first-child)::before{content:"";position:absolute;top:31px;right:50%;width:calc(100% + 1rem);height:4px;background:var(--ridgeline);opacity:.5;z-index:0;border-radius:2px}
    .rv-process-node{position:relative;z-index:1;width:64px;height:64px;border-radius:50%;display:inline-flex;align-items:center;justify-content:center;font-family:var(--font-display);font-weight:800;font-size:1.5rem;color:#fff;background:var(--color-pine);border:3px solid var(--color-paper,#fff);box-shadow:0 8px 18px color-mix(in srgb,var(--color-pine) 32%,transparent)}
    .rv-process-t{margin:.9rem 0 .3rem;font-family:var(--font-display);font-size:1.05rem;font-weight:700;color:var(--color-ink)}
    .rv-process-d{margin:0 auto;max-width:22ch;font-size:.86rem;color:var(--color-muted);line-height:1.45}
    .rv-process-note{margin:clamp(2rem,4vw,2.75rem) 0 0;text-align:left;font-family:var(--font-mono);font-size:.78rem;letter-spacing:.04em;text-transform:uppercase;color:var(--color-pine)}
    @media(max-width:860px){.rv-faqproc .rv-process{grid-template-columns:1fr;gap:1.6rem;position:relative;max-width:34rem}.rv-faqproc .rv-process::before{content:"";position:absolute;left:31px;top:32px;bottom:32px;width:4px;background:var(--ridgeline);opacity:.4;border-radius:2px}.rv-process-step{display:grid;grid-template-columns:auto 1fr;gap:.15rem 1.15rem;text-align:left;align-items:center}.rv-process-step:not(:first-child)::before{display:none}.rv-process-node{grid-row:span 2}.rv-process-t{margin:0;align-self:end}.rv-process-d{margin:0;align-self:start;max-width:none}.rv-process-note{text-align:left}}
    @media(prefers-reduced-motion:no-preference){.rv-process-node{transition:transform .15s ease}.rv-process-step:hover .rv-process-node{transform:translateY(-3px)}}

    /* FAQ groups — all open */
    .rv-faqwrap .rv-faqcat{margin-top:clamp(2.5rem,5vw,3.5rem)}
    .rv-faqcat-h{font-family:var(--font-display);font-weight:800;font-size:clamp(1.3rem,2.7vw,1.85rem);letter-spacing:-.01em;color:var(--color-ink);margin:0 0 1.35rem;padding-bottom:.65rem;border-bottom:2px solid var(--color-line)}
    .rv-faqgrid{display:grid;grid-template-columns:repeat(auto-fit,minmax(330px,1fr));gap:1.1rem}
    .rv-qa{position:relative;overflow:hidden;background:var(--color-paper,#fff);border:1px solid var(--color-line);border-radius:var(--radius-lg,16px);padding:1.4rem 1.5rem 1.4rem 1.7rem;transition:transform .15s ease,box-shadow .2s ease}
    .rv-qa::before{content:"";position:absolute;left:0;top:0;bottom:0;width:4px;background:var(--ridgeline)}
    .rv-qa:hover{transform:translateY(-2px);box-shadow:var(--shadow-soft)}
    .rv-qa-q{font-family:var(--font-display);font-size:1.12rem;font-weight:700;color:var(--color-ink);margin:0 0 .5rem;line-height:1.25}
    .rv-qa-a{margin:0;color:var(--color-body);line-height:1.65}
  </style>
@endsection
